name: Deploy Static Site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Basic Build Step
      run: echo "✅ Build Successful!"
